version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - customers-network
volumes:
  dbdata6:
networks:
  customers-network:
    driver: bridge
